apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2-deployment
  labels:
    app: container2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
      - name: container2
        image: us-central1-docker.pkg.dev/kube-429214/my-k8-repo
        imagePullPolicy: Always
        ports:
        - containerPort: 6001
        volumeMounts:
        - mountPath: /shifa_PV_dir
          name: shifa-storage
      volumes:
      - name: shifa-storage
        persistentVolumeClaim:
          claimName: shifa-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: container2-service
spec:
  selector:
    app: container2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6001
  type: LoadBalancer
